language: Snakemake
name: sequana_ribofinder
description: Simple workflow to find ribosomal in a set of FastQ files
url: https://github.com/sequana/sequana_ribofinder/blob/master/sequana_pipelines/ribofinder/ribofinder.rules
categories: [NGS, snakemake, sequana]
authors:
    - firstname: Thomas
      lastname: Cokelaer
      email: thomas.cokelaer@pasteur.fr

